project:
  type: manuscript

manuscript:
  article: index.qmd
  
  notebooks:
  - notebook: notebooks/profile_cancer_data.qmd
    title: Profile cancer data
  - notebook: notebooks/eda_cancer_data.qmd
    title: Exploratory data analisys

  code-links:
    - text: GitHub
      icon: github
      href: https://github.com/ManuelLagunas/cancer_detection.git

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

execute:
  freeze: auto